config/routes.rb
Codebnb::Application.routes.draw do


  root :to => "home#index"

  match '/signout' => 'sessions#destroy', :as => :signout
  match '/signin' => 'sessions#new', :as => :signin
  match '/auth/:provider/callback', to: 'sessions#create'

  resource :profile, module: :user do
    resources :venues do
      resources :periods
    end

    resource :requests do
      match 'accept/:reservation' => 'user/requests#accept', :via => :post, :as => :accept
      match 'decline/:reservation' => 'user/requests#decline', :via => :post, :as => :decline
    end
  end

  resources :venues do
    collection do
      get :near
    end
    resources :reservations, module: :venues
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :latitude, :longitude, :title, :url, :address
  reverse_geocoded_by :latitude, :longitude, :address => :location
  after_validation :reverse_geocode

end

app/models/period.rb
class Period < ActiveRecord::Base
  belongs_to :venue
  has_many :reservations

  attr_accessible :ends, :start

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :user
  belongs_to :venue
  belongs_to :period

  attr_accessible :status

  def self.requests(user_id)
    joins(:period => :venue)
      .where(:venues => {user_id: user_id})
      .where(:status => :pending)
  end

  def self.request(venue_id, hoster_id, user_id)
    requests(hoster_id).where(user_id: user_id)
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :venues
  has_many :reservations
  attr_accessible :provider, :uid, :name, :email, :first_name, :last_name, :age, :address, :city, :state, :country, :zip_code

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      if auth['info']
         user.name = auth['info']['name'] || ""
         user.email = auth['info']['email'] || ""
      end
    end
  end

end

app/models/venue.rb
class Venue < ActiveRecord::Base
  belongs_to :user
  belongs_to :city

  has_many :periods

  attr_accessible :description, :disclamer, :internet, :label, :latitude, :longitude,
                  :mates_allowed, :mates_quantity, :meals, :work_place, :name, :rooms

  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode

end

app/models/venue_image.rb
class VenueImage < ActiveRecord::Base
  belongs_to :venue_id
  attr_accessible :resource
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  helper_method :user_signed_in?
  helper_method :correct_user?

  private
    def current_user
      begin
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
      rescue Mongoid::Errors::DocumentNotFound
        nil
      end
    end

    def user_signed_in?
      return true if current_user
    end

    def correct_user?
      @user = User.find(params[:id])
      unless current_user == @user
        redirect_to root_url, :alert => "Access denied."
      end
    end

    def authenticate_user!
      if !current_user
        redirect_to root_url, :alert => 'You need to sign in for access to this page.'
      end
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def near
    @venues = Venue.near([params[:lat], params[:lon]], params[:radius])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to '/auth/github'
  end


  def create
    auth = request.env["omniauth.auth"]
    user = User.where(:provider => auth['provider'],
                      :uid => auth['uid'].to_s).first || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    if user.email.blank?
      redirect_to edit_user_path(user), :alert => "Please enter your email address."
    else
      url = params[:request_path] ? params[:request_path] : root_url
      redirect_to url, :notice => 'Signed in!'
    end

  end

  def destroy
    reset_session
    redirect_to root_url, :notice => 'Signed out!'
  end

  def failure
    redirect_to root_url, :alert => "Authentication error: #{params[:message].humanize}"
  end

end

app/controllers/user/periods_controller.rb
class User::PeriodsController < UserController

  def new
    @venue = venue
    @periods = venue.periods
    @period = venue.periods.new
  end

  def show

  end

  def create
    if (@period = venue.periods.create params[:period])
      flash[:notice] = "Period Created!"
      redirect_to profile_venues_path()
    else
      flash[:erro] = "Errors #{@period.errors}"
      render :new
    end
  end

  def destroy
    @period = Period.find params[:id]
    @period.delete
    redirect_to profile_venues_path
  end

  protected

  def venue
    current_user.venues.find(params[:venue_id])
  end

end

app/controllers/user/profiles_controller.rb
class User::ProfilesController < UserController

  def edit
    @user = current_user
  end

  def update
    if current_user.update_attributes params[:user]
      flash[:notice] = 'Success!'
    else
      flash[:error] = 'Something was wrong, #{current_user.errors}'
    end
  end

end

app/controllers/user/requests_controller.rb
class User::RequestsController < UserController
  def show
    @reservations = reservations
  end

  def accept
    reservation.update_attribute :status, :accepted
  end

  def decline
    reservation.update_attribute :status, :declined
  end

  protected

  def reservations
    Reservation.requests current_user.id
  end

  def reservation
    Reservation.request params[:venue_id], params[:reservation], current_user.id
  end

end

app/controllers/user/venues_controller.rb
class User::VenuesController < UserController

  def index
    @venues = current_user.venues
  end

  def edit
    @venue = current_user.venues.find(params[:id])
  end

  def new
    @venue = current_user.venues.build
  end

  def create
    if (@venue = current_user.venues.create(params[:venue]))
      flash[:notice] = "Venue Created!"
      redirect_to action: :index
    else
      flash[:error] = "Errors #{@venue.errors}"
      render :index
    end
  end

  def update
    @venue = current_user.venues.find(params[:id])
    if @venue.update_attributes(params[:venue])
      flash[:notice] = 'Venue Updated'
      redirect_to action: :index
    else
      flash[:error] = "Errros #{@veneu.errrors}"
      render :index
    end
  end

  def destroy
    @venue = current_user.venues.find(params[:id])
    @venue.delete
    redirect_to action: :index
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController

  before_filter :authenticated

  def authenticated
    redirect_to "/auth/github?request_path=#{request.path}" unless current_user
  end

end

app/controllers/venues/reservations_controller.rb
class Venues::ReservationsController < ApplicationController
  respond_to :html, :json

  def index
    @periods = venue.periods
  end

  def create
    respond_with(@reservation = period.reservations.create(status: :applyed, user: current_user))
  end

  def destroy
  end

  def show
    @periods = venue.periods
  end


  protected

  def venue
    current_user.venues.find(params[:venue_id])
  end

  def period
    venue.periods.find(params[:id])
  end

end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController

  def show
    @venue = Venue.where(id: params[:id]).includes(:periods)
  end

  def near
    respond_to do |format|
      format.js { render json: Venue.near([params[:lat], params[:long]], params[:rad]) }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_image(email, size)
    hash = Digest::MD5.hexdigest(email)
    "https://secure.gravatar.com/avatar/#{hash}?s=#{size}"
  end

  def select_tab(tab)
    if controller_name == tab
      'active'
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/venues/booking_helper.rb
module Venues::BookingHelper
end

app/views/home/index.html.haml
#home.row
  .span4#venue_list
    - 5.times do
      .well
        .row
          .span1
            %a.thumbnail{:href => "http://critterapp.pagodabox.com/others/admin"}
              %img{:alt => "", :src => "http://critterapp.pagodabox.com/img/user.jpg"}/
          .span2
            %p admin
            %strong
              %p First Last Name
        .row
          .span3
            %span.badge.badge-warning 8 messages
            %span.badge.badge-info 15 followers
  .span8
    #venues_map

#venue-info.modal.hide.fade
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
    %h3 Venue info
  .modal-body
    %p
  .modal-footer
    %a.btn{:href => "#"} Close
    %a.btn.btn-primary{:href => "#"} Book!

:javascript
  $(function() {
    window.google_maps = new Codebnb.google_maps;
    window.google_maps.initMap()
  });

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
.row
  .span12
    = link_to root_path, class: 'pull-right' do
      = image_tag 'logo.png'
#main-navbar.navbar.navbar-static
  .navbar-inner
    .container{:style => "width: auto;"}
      %form.navbar-search.pull-left
        %input.search-query.span2{:placeholder => "Search", :type => "text"}
        %select.multiple.span2
          %option 1
          %option 2
      %ul.nav.pull-right
        - unless user_signed_in?
          %li
            = link_to signin_path do
              Login
        - else
          %li#fat-menu.dropdown
            %a#drop3.dropdown-toggle{"data-toggle" => "dropdown", :href => "#", :role => "button"}
              #{current_user.name}
              %b.caret
            %ul.dropdown-menu{"aria-labelledby" => "drop3", :role => "menu"}
              %li
                %a{:href => "#", :tabindex => "-1"} My profile
              %li
                %a{:href => "#", :tabindex => "-1"} Venues?
              %li.divider
              %li
                = link_to signout_path, tabindex: "-1" do
                  %i.icon-off
                  Log out

app/views/layouts/_user_navigation.html.haml
.row
  .span12
    = link_to root_path, class: 'pull-right' do
      = image_tag 'logo.png'
#main-navbar.navbar.navbar-static
  .navbar-inner
    .container{:style => "width: auto;"}
      %ul.nav
        %li{class: "#{select_tab 'profiles'}"}
          = link_to 'My profile', edit_profile_path
        %li{class: "#{select_tab 'venues'}"}
          = link_to 'My Venues', profile_venues_path
        %li{class: "#{select_tab 'request'}"}
          = link_to 'Requests', profile_requests_path
      %ul.nav.pull-right
        - unless user_signed_in?
          %li
            = link_to signin_path do
              Login
        - else
          %li#fat-menu.dropdown
            %a#drop3.dropdown-toggle{"data-toggle" => "dropdown", :href => "#", :role => "button"}
              #{current_user.name}
              %b.caret
            %ul.dropdown-menu{"aria-labelledby" => "drop3", :role => "menu"}
              %li
                = link_to 'My profile', edit_profile_path
              %li
                %a{:href => "#", :tabindex => "-1"} Venues?
              %li.divider
              %li
                = link_to signout_path, tabindex: "-1" do
                  %i.icon-off
                  Log out

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Codebnb"
      %meta{:content => "initial-scale=1.0, user-scalable=no", :name => "viewport"}
      %meta{:content => content_for?(:description) ? yield(:description) : "Codebnb", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        %script{:src => "http://maps.googleapis.com/maps/api/js?key=AIzaSyCsUI6T9rdz59eW1ckzT-XgHHB9qcG2SfI&sensor=true", :type => "text/javascript"}
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
  %body
    #container.container
      %header
        = render 'layouts/navigation'
        = render 'layouts/messages'
      #main{:role => "main"}
        = yield
      %footer
    / ! end of #container

app/views/layouts/user.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Codebnb"
      %meta{:content => "initial-scale=1.0, user-scalable=no", :name => "viewport"}
      %meta{:content => content_for?(:description) ? yield(:description) : "Codebnb", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        %script{:src => "http://maps.googleapis.com/maps/api/js?key=AIzaSyCsUI6T9rdz59eW1ckzT-XgHHB9qcG2SfI&sensor=true", :type => "text/javascript"}
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
  %body
    #container.container
      %header
        = render 'layouts/user_navigation'
        = render 'layouts/messages'
      #main{:role => "main"}
        = yield
      %footer
    = yield :scripts

app/views/user/periods/_form.html.haml
%h3.lead.section-titles Select an Availabitly period of time for your venue
.well
  #alert.alert.alert-error{:style => "display: none; "}
    %strong
  %table.table
    %thead
      %tr
        %th
          Start date
          %a#dp4.btn.small{"data-date" => "#{Date.today}", "data-date-format" => "yyyy-mm-dd", :href => "#"} Change
        %th
          End date
          %a#dp5.btn.small{"data-date" => "#{Date.today}", "data-date-format" => "yyyy-mm-dd", :href => "#"} Change
    %tbody
      %tr
        %td#startDate
        %td#endDate

= form_for [:profile, :venue, @period], class: 'form-horizontal' do |f|
  = f.hidden_field :start
  = f.hidden_field :ends
  .control-group
    / Form Actions
    .form-actions
      %button.btn.btn-primary.pull-right{:type => "submit"} Save changes

%table.table.table-striped
  %thead
    %thead
      %tr
        %th id
        %th start time
        %th Ends time
        %th

    %tbody
      = render @periods



:coffeescript
  startDate = new Date()
  endDate = new Date()
  $("#dp4").datepicker().on "changeDate", (ev) ->
    if ev.date.valueOf() > endDate.valueOf()
      $("#alert").show().find("strong").text "The start date can not be greater then the end date"
    else
      $("#alert").hide()
      startDate = new Date(ev.date)
      $("#startDate").text $("#dp4").data("date")
      $('#period_start').val $("#dp4").data("date")
    $("#dp4").datepicker "hide"

  $("#dp5").datepicker().on "changeDate", (ev) ->
    if ev.date.valueOf() < startDate.valueOf()
      $("#alert").show().find("strong").text "The end date can not be less then the start date"
    else
      $("#alert").hide()
      endDate = new Date(ev.date)
      $("#endDate").text $("#dp5").data("date")
      $('#period_ends').val $("#dp5").data("date")
    $("#dp5").datepicker "hide"

app/views/user/periods/_period.html.haml
%tr
  %td= period.id
  %td= period.start
  %td= period.ends
  %td
    = link_to profile_venue_period_path(@venue.id, period.id), class: 'btn btn-danger',
      method: 'delete', confirm: 'Qre you sure?' do
      %i.icon-trash.icon-white

app/views/user/periods/new.js.haml
$('#venue-form').html("#{escape_javascript(render 'user/periods/form', collection: @period)}");

app/views/user/profiles/edit.html.haml
.row
  .span4
    %ul.thumbnails
      %li.span3
        %a.thumbnail{:href => "#"}
          = image_tag(gravatar_image(current_user.email, 210))
  .span8
    = form_for @user, url: profile_path, :method => :put, class: 'form-horizontal' do |f|
      %fieldset
        #legend
          %legend Basic Info
        .control-group
          / Text input
          = f.label :name, class: 'control-label'
          .controls
            = f.text_field :name, class: 'input-xlarge'
        .control-group
          / Text input
          = f.label :age, class: 'control-label'
          .controls
            = f.text_field :age, class: 'input-xlarge'
        .control-group
          / Text input
          = f.label :address, class: 'control-label'
          .controls
            = f.text_field :address, class: 'input-xlarge'
        .control-group
          / Text input
          = f.label :city, class: 'control-label'
          .controls
            = f.text_field :city, class: 'input-xlarge'
        .control-group
          / Text input
          = f.label :state, class: 'control-label'
          .controls
            = f.text_field :state, class: 'input-xlarge'
        .control-group
          / Text input
          = f.label :country, class: 'control-label'
          .controls
            = f.text_field :country, class: 'input-xlarge'
        .control-group
          / Text input
          = f.label :zip_code, class: 'control-label'
          .controls
            = f.text_field :zip_code, class: 'input-xlarge'
        .control-group
          / Form Actions
          .form-actions
            %button.btn.btn-primary.pull-right{:type => "submit"} Save changes

app/views/user/profiles/index.html.haml
= link_to 'edit', edit_profile_path

app/views/user/profiles/show.html.haml
= link_to 'Edit', edit_profile_path
= link_to 'My Venues', profile_venues_path

app/views/user/profiles/update.html.haml
%h1 Profile#update
%p Find me in app/views/profile/update.html.haml

app/views/user/requests/_reservation.html.haml
%tr
  %td= link_to reservation.period.venue.label, ''
  %td= link_to reservation.user.name
  %td
    = link_to  '', class: 'btn btn-success' do
      %i.icon-check.icon-white
      Accept
    = link_to '', class: 'btn btn-danger' do
      %i.icon-trash.icon-white
      Reject

app/views/user/requests/show.html.haml
#request.row
  .offset2.span8
    %h3.lead.section-titles My Requests

    %table.table.table-striped
      %thead
        %tr
          %th Venue
          %th Tenant
          %th
      %tbody
        = render partial: 'user/requests/reservation', collection: @reservations

app/views/user/venues/_form.html.haml
= form_for [:profile, @venue], class: 'form-horizontal' do |f|
  %fieldset
    #legend
      %legend New Venue
    .control-group
      / Text input
      = f.label :label, class: 'control-label'
      .controls
        = f.text_field :label, class: 'input-large'
    .control-group
      .controls
        = link_to 'I want a different place!', '#', id: 'different-place'
        .address.hidden
          .alert.alert-error.hidden
            %h4 Aww men!
            Please try again, we couldn't find your location
          = text_field_tag 'address', nil, class: 'input-large', placeholder: 'address'
          = text_field_tag 'city', nil, class: 'input-medium', placeholder: 'city'
          = text_field_tag 'state', nil, class: 'input-small', placeholder: 'state'
          = text_field_tag 'zip-code', nil, class: 'input-small', placeholder: 'zip code'
          = link_to 'Find location', '#', id: 'find_location', class: 'btn'
      #venues_map
        ss
    .control-group
      / Text input
      = label_tag '','latitude & longitude', class: 'control-label'
      .controls
        = f.text_field :latitude, class: 'input-small'
        = f.text_field :longitude, class: 'input-small'
    .control-group
      / Text input
      = f.label :description, class: 'control-label'
      .controls
        = f.text_area :description, class: 'input-large', rows: '3'
    .control-group
      / Text input
      = f.label :rooms, class: 'control-label'
      .controls
        = f.number_field :rooms, class: 'input-large'
    .control-group
      / Text input
      = f.label :disclamer, class: 'control-label'
      .controls
        = f.text_field :disclamer, class: 'input-large'
    .control-group
      %label.checkbox.inline
        = f.check_box :work_place
        Work place
      %label.checkbox.inline
        = f.check_box :meals
        Meals
      %label.checkbox.inline
        = f.check_box :internet
        Internet
      %label.checkbox.inline
        = f.check_box :mates_allowed
        Mates allowed
    .control-group
      / Text input
      = f.label :mates_quantity, class: 'control-label'
      .controls
        = f.text_field :mates_quantity, class: 'input-large'
    .control-group
      / Form Actions
      .form-actions
        %button.btn.btn-primary.pull-right{:type => "submit"} Save changes

app/views/user/venues/_venue.html.haml
%tr
  %td.span2= venue.label
  %td.span3
    = link_to 'Edit', edit_profile_venue_path(venue.id), remote: true, class: 'btn btn-info'
    = link_to new_profile_venue_period_path(venue.id), remote: true, class: 'btn btn-info' do
      %i.icon-calendar.icon-white
    = link_to profile_venue_path(venue.id), class: 'btn btn-danger', method: 'delete', confirm: 'Are you sure' do
      %i.icon-trash.icon-white
      Delete

app/views/user/venues/edit.js.haml
$('#venue-form').html("#{escape_javascript(render 'user/venues/form', collection: @venue)}");
window.google_maps.loadMap("#{@venue.latitude}", "#{@venue.longitude}");

app/views/user/venues/index.html.haml
.row
  .span5
    %h3.lead.section-titles
      My Venues
      = link_to 'Create Venue', new_profile_venue_path, remote: true, class: 'pull-right'

    %table.table.table-striped
      %thead
        %thead
          %tr
            %th Venue
            %th Options
        %tbody
          = render @venues

  #venue-form.span7
:coffeescript
  $ ->
    window.venue_profile = new Codebnb.venue_profile
    window.google_maps = new Codebnb.google_maps

app/views/user/venues/new.js.haml
$('#venue-form').html("#{escape_javascript(render 'user/venues/form', collection: @venue)}");
window.google_maps = new Codebnb.google_maps;